name: Build

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      # ensure  new-enough CMake (i.e. >= 3.28)
      - name: Install CMake (3.28+) and Ninja
        uses: lukka/get-cmake@v4.2.2
        with:
          cmakeVersion: 3.28.3


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            clang-18 clang-tools-18 lld-18 \
            pkg-config \
            libzip-dev zipmerge zipcmp \
            zip

      - name: Configure
        run: |
          which clang-18
          which clang++-18
          which clang-scan-deps-18

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=clang-18 \
            -DCMAKE_CXX_COMPILER=clang++-18 \
            -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS=/usr/bin/clang-scan-deps-18

      - name: Build
        run: cmake --build build --parallel

      - name: Test (if any)
        run: ctest --test-dir build --output-on-failure
